### ISSUE TITLE
Implement option1 and option2 for GRAIN and STT

### ISSUE THREAD

**Issue by mt82** [DUNE-ND-SAND/dunendggd#14]
See [issue 12](https://github.com/DUNE-ND-SAND/dunendggd/issues/12)

**Comment by mt82** [comment]
I created a [branch](https://github.com/DUNE-ND-SAND/dunendggd/tree/14-implement-option1-and-option2-for-GRAIN-and-STT) for this issue

@bingguo1 should implement the STT configuration with the upstream modules removed so that it fit with the new volume. The implementation should go [here](https://github.com/DUNE-ND-SAND/dunendggd/blob/f8621637155d73c13a4182d155aa9ec6dc2eae39/duneggd/SubDetector/STTFULL_oct2021_v2.py#L710)

@jabb4 should implement old GRAIN configuration (that with less thickness). Modification should go [here](https://github.com/DUNE-ND-SAND/dunendggd/blob/f8621637155d73c13a4182d155aa9ec6dc2eae39/duneggd/SubDetector/Grain.py#L224)

**Comment by bingguo1** [comment]
@mt82  just added option2
NOTE: since @jabb4 have dedicated Grain.py to work on, i commented lines about grain in "STTFULL_oct2021_v2.py"
@jabb4 , I tried to generate gdml with grain and stt together, but there's error comes out of Grain.py, "self.HoneycombThickness  = Q("50mm")" only defined in option1 but not in option2
I suppose self.HoneycombThickness are the same for both options?  To make it run, i took this line out of "if-else", then it ran smoothly. However, i recognize an overlapping issue :

```
Info in <TGeoNodeMatrix::CheckOverlaps>: Checking overlaps for volWorld and daughters within 1e-05
Check overlaps:      [==========] 44881 [100.00 %]           00:00           
Info in <TGeoNodeMatrix::CheckOverlaps>: Number of illegal overlaps/extrusions : 1

=== Overlaps for Default ===
 = Overlap ov00000: vacuum_gap_between_vessels_lv extruded by: vacuum_gap_between_vessels_lv/Aluminum_layer_inner_vessel_lv_0 ovlp=1.4
```

**Comment by bingguo1** [comment]
@jabb4 I just realize there's no **return** in option2 function in Grain.py,  and the final Grain volume name in final gdml is even not fixed.

**Comment by mt82** [comment]
I agree with @bingguo1. Function [`construct_GRAIN_option1`](https://github.com/DUNE-ND-SAND/dunendggd/blob/58df840e9d40dfab509af7b9df10ea6024aed235/duneggd/SubDetector/Grain.py#L268) in Grain.py should return a volume. 
@jabb4 I would suggest to replace line 382 with `return Ext_vessel_lv`

**Comment by jabb4** [comment]
@bingguo1 @mt82 I should have fixed the issue, and now you should be able to generate both the geometries. 
Nevertheless I see other overlaps here:
![tracker_overlap](https://user-images.githubusercontent.com/48324147/139826755-0c1fdab7-d252-4b69-a6b1-d8716ff7a129.png)

**Comment by bingguo1** [comment]
@jabb4  Is this overlapping happen to option1 or option2, I just generated new gdmls for both and didn't see any overlapping.  What is that external long blue cube?  is that belong to SAND? What overlapping exactly? 
I suggest you use following lines to produce overlapps:
```
	TGeoManager *geo = new TGeoManager();
geo->Import("/Users/bing/physicswork/sandggd3/dunendggd/SAND_opt2.gdml")
    geo->CheckOverlaps(1e-5,"d");
	geo->PrintOverlaps();
```

Naming suggestions, @jabb4 , if you take a look into gdml file itself, you gonna see,  in option1, grain1 name is called "Ext_vessel_lv", grain2 is called "Ext_vessel_outern_Carbon_fiber_layer_lv",  they are not same and too long, i suggest simply give it name something like "grain" .

 ```
<volume name="Ext_vessel_lv">
      <materialref ref="Carbon_fiber"/>
      <solidref ref="Ext_vessel_shape"/>
      <physvol>
        <volumeref ref="vacuum_gap_between_vessels_lv"/>
        <positionref ref="center"/>
        <rotationref ref="identity"/>
      </physvol>
      <physvol>
        <volumeref ref="EndCap1_ExtVessel_lv"/>
        <positionref ref="EndCap1_ExtVessel_pos"/>
        <rotationref ref="identity"/>
      </physvol>
      <physvol>
        <volumeref ref="EndCap2_ExtVessel_lv"/>
        <positionref ref="EndCap2_ExtVessel_pos"/>
        <rotationref ref="identity"/>
      </physvol>
    </volume>
```
It seems all your names are hardly grain identifiable, I suggest you rename them to be like "grain_****" pattern

**Comment by mt82** [comment]
I confirm: no overlap neither in opt1 nor in opt2.
If I understand correctly, @jabb4 checked overlaps by eye on the
display. This is not the right way to check. What you see in the display
is, probably, the boolean (subtraction) volume of the STT not properly
managed by the display.

**Comment by jabb4** [comment]
I have checked in the following way, but i might be wrong as I am not root expert at all :)
![image](https://user-images.githubusercontent.com/48324147/139862646-dffafe39-82af-4755-affc-74bf42c59036.png)
Where am I wrong?

**Comment by mt82** [comment]
I use this commit [`3c1312c28a7e4187a9e75f34695813dac72ae896`](https://github.com/DUNE-ND-SAND/dunendggd/commit/3c1312c28a7e4187a9e75f34695813dac72ae896), which correspond to your last commit on remote branch `14-implement-option1-and-option2-for-GRAIN-and-STT`

**Comment by mt82** [comment]
### OPTION 1
![SAND_opt1](https://user-images.githubusercontent.com/7208136/139867401-05baa8a8-e7a3-4175-b41e-a87a9d00991a.png)

### OPTION 2
![SAND_opt2](https://user-images.githubusercontent.com/7208136/139867486-6956b7ab-3a90-46bb-9a1d-d898abc1b5fe.png)

**Comment by mt82** [comment]
Please @jabb4, confirm us everything is ok, so that we submit a merge request and close the issue

**Comment by jabb4** [comment]
@mt82 before merging I want to rename some volumes as suggested by @bingguo1. I am currently working on it.

**Comment by bingguo1** [comment]
Looks like the overlapping from @jabb4  your screenshots are between volWorld and its daughter, did u make any change to any cfg files, i'm pretty sure they are okay if you keep them the same.
u can run following command which  should produce no overlapping
```
gegede-cli duneggd/Config/WORLDggd.cfg \
           duneggd/Config/ND_Hall_Air_Volume_Only_KLOE.cfg \
           duneggd/Config/ND_Hall_Rock.cfg \
           duneggd/Config/KLOE_STTFULL.cfg \
           duneggd/Config/SANDINNERVOLOPT2.cfg \
           duneggd/Config/KLOEEMCALO.cfg \
           duneggd/Config/STT.cfg \
           duneggd/Config/GRAIN.cfg \
           -w World -o SAND_opt2.gdml
```
you can comment out STT  in cfg if you want to reduce the generation time

**Comment by bingguo1** [comment]
@mt82 @jabb4  in build_hall.sh, when I run the opt1 or opt2, i ran into problems due to python files(many of them are python2/3 issues) from other detectors, do you agree i reduce lines to get rid of other detector cfg like what I showed above? that will make our developers run into less issues

**Comment by jabb4** [comment]
@bingguo1 I did not make any change to any cfg files....anyway the fact is that now the Checkoverlaps() function does not find any illegal overlap for both geometries (even though i see it when drawing...don't know actually why).

I have now set more reasonable names for GRAIN components, so @bingguo1 @mt82  please let me know if now everything is ready to be merged

**Comment by bingguo1** [comment]
@jabb4  you have many variables and lines repeat in option1 and option2, they eventually need to be consistent within their gdml output, this makes the code sort of fragile. But i think it's okay for now.

**Comment by mt82** [comment]
Ok, I will make the pull request
By the way, @bingguo1 and @jabb4, could you please make a presentation of these implementation at Friday meeting?

**Comment by jabb4** [comment]
@bingguo1 I did not make any change to any cfg files....anyway the fact is that now the Checkoverlaps() function does not find any illegal overlap for both geometries (even though i see it when drawing...don't know actually why).

I have now set more reasonable names for GRAIN components, so @bingguo1 @mt82  please let me know if now everything is ready to be merged
