### ISSUE TITLE
ECAL endcap container shape leads to  GENIE generation issue

### ISSUE THREAD

**Issue by bingguo1** [DUNE-ND-SAND/dunendggd#15]
@mt82  @jabb4 The ECAL endcaps are made by endcap slices with rmin>0, but if the container of endcap is also made with same rmin, the GENIE will generate events in weird positions. However if i set the parent volumes to use tub with rmin=0, the problem will be solved. I'll make changes to the rmin for the two containers of endcaps, if you don't disagree.

**Comment by mt82** [comment]
@bingguo1 could you explain me how to reproduce the issue? I would like to investigate if the issue is related to GENIE
or to the GDML. For the former, I would notify it to GENIE support.

**Comment by bingguo1** [comment]
Use the geometry generated by current config, and try to generate some events in ECAL endcap with GENIE, then plot the vertex distribution. In the past, I observed some weird distribution. If @mt82 or someone else can double check it, that would be great. It's a good idea to report to GENIE people.

**Comment by mt82** [comment]
![VtxYZ](https://user-images.githubusercontent.com/7208136/140060637-22196963-6e7a-40d2-8776-34400f24c98e.png)
I confirm. I will try to check the same happens with a dummy Tube geometry
